title: Parker Allen # your name (or website title) here
logo: "/images/Me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently I am a Eastern Michigan University Computer Science student. I like to make video games by myself(<a href="https://griny.itch.io/" target="_blank">my itch.io page</a>) and in a college club (<a href=https://sgwdev.org/" target="_blank">sgwdev.org</a>).
  <br><br>
  <a href="https://www.linkedin.com/in/parker-allen-9953161a2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
